import com.sun.tools.doclets.formats.html.SourceToHTMLConverter;
import com.sun.tools.internal.ws.wsdl.document.soap.SOAPUse;
import com.sun.tools.javah.Gen;
import com.sun.xml.internal.bind.v2.model.core.ID;
import javax.xml.transform.Result;
import java.io.FileInputStream;
import java.sql.*;
import java.util.Properties;
import java.util.Scanner;


public class BankingSystem {
	private static String driver;
	private static String url;
	private static String username;
	private static String password;
	
	private static Connection con;
	private static Statement stmt;
	private static ResultSet rs;

	private static Scanner scanner = new Scanner(System.in);

	//Current id
	private static String currentID;


	public static void init(String filename) {
		try {
			Properties props = new Properties();						// Create a new Properties object
			FileInputStream input = new FileInputStream(filename);	// Create a new FileInputStream object using our filename parameter
			props.load(input);										// Load the file contents into the Properties object
			driver = props.getProperty("jdbc.driver");				// Load the driver
			url = props.getProperty("jdbc.url");						// Load the url
			username = props.getProperty("jdbc.username");			// Load the username
			password = props.getProperty("jdbc.password");			// Load the password
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	

	public static void testConnection() {
		System.out.println(":: TEST - CONNECTING TO DATABASE");
		try {
			Class.forName(driver);
			con = DriverManager.getConnection(url, username, password);
			con.close();
			System.out.println(":: TEST - SUCCESSFULLY CONNECTED TO DATABASE");
			} catch (Exception e) {
				System.out.println(":: TEST - FAILED CONNECTED TO DATABASE");
				e.printStackTrace();
			}
	  }

	public static void createTables() {
		try {
			Class.forName(driver);
			con = DriverManager.getConnection(url, username, password);
			String dropCustomer = "DROP TABLE P1.CUSTOMER";
			PreparedStatement drops1 = con.prepareStatement(dropCustomer);
			drops1.executeUpdate();
			drops1.close();
			String dropAccount = "DROP TABLE P1.ACCOUNT";
			PreparedStatement drops2 = con.prepareStatement(dropAccount);
			drops2.executeUpdate();
			drops2.close();
			String dropView = "DROP VIEW P1.TOTAL_BALANCE";
			PreparedStatement drops3 = con.prepareStatement(dropView);
			drops3.executeUpdate();
			drops3.close();
			String createCustomer = "CREATE TABLE P1.CUSTOMER(ID INT GENERATED BY DEFAULT AS IDENTITY(START WITH 100 INCREMENT BY 1), Name VARCHAR(15) NOT NULL, Gender CHAR(1) NOT NULL CHECK (Gender = 'M' OR Gender = 'F'), Age INT NOT NULL CHECK (Age >= 0), Pin INT NOT NULL CHECK(Pin >= 0) , PRIMARY KEY (ID))";
			PreparedStatement createStatement = con.prepareStatement(createCustomer);
			createStatement.executeUpdate();
			createStatement.close();
			String accountTable = "CREATE TABLE P1.ACCOUNT (Number INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000 INCREMENT BY 1), ID INT NOT NULL, Balance INT NOT NULL CHECK(Balance >= 0), Type CHAR(1) NOT NULL CHECK(Type = 'C' OR Type =  'S'), Status CHAR(1) NOT NULL CHECK(Status = 'A'OR Status = 'I'), PRIMARY KEY (Number), FOREIGN KEY (ID) REFERENCES P1.CUSTOMER (ID))";
			PreparedStatement createStatement2 = con.prepareStatement(accountTable);
			createStatement2.executeUpdate();
			createStatement2.close();
			String viewer = "CREATE VIEW P1.TOTAL_BALANCE(ID, TOTAL) AS SELECT ID, SUM(BALANCE) FROM P1.ACCOUNT GROUP BY ID";
			PreparedStatement viewerStatement = con.prepareStatement(viewer);
			viewerStatement.executeUpdate();
			viewerStatement.close();
			con.close();
			System.out.println(":: CREATED DATABASE SUCCESSFULLY");
		} catch (Exception re) {
			System.out.println(":: GOT ERROR WHEN CREATING DATABASES");
			re.printStackTrace();
		}
	}

	public static void start(){
		welcomePage();
	}

	private static void welcomePage(){
		System.out.println(":: Welcome to the Self Services Banking System! – Main Menu");
		System.out.println("1.New Customer\n" + "2.Customer Login\n" + "3.Exit");
		if(scanner.hasNextLine()){
			String input = scanner.nextLine();
			if(input.length() > 1 || input.isEmpty()) {
				System.out.println("Enter a valid number to start.");
				welcomePage();
			}
			else {
				switch (input) {
					case "1":
						signupFunction();
						welcomePage();
						break;
					case "2":
						loginFunction();
						welcomePage();
						break;
					case "3":
						scanner.close();
						System.exit(0);
						break;

				}
			}
		}
	}

	private static void customerPage(){
		System.out.println("Customer Page:\n1.Open Account\n" + "2.Close Account\n" + "3.Deposit\n" + "4.Withdraw\n" + "5.Transfer\n" + "6.Account Summary\n" + "7.Exit");
		if(scanner.hasNextLine()){
			String selection = scanner.nextLine();
			switch (selection){
				case "1":
					System.out.println("OPEN NEW ACCOUNT");
					System.out.println("ID:");
					String id = scanner.nextLine();
					System.out.println("Account Type \n" + "Enter 'C' for Checking account OR 'S' for Saving account");
					String type = scanner.nextLine();
					System.out.println("Initial Deposit Amount");
					String deposit = scanner.nextLine();
					if(!id.isEmpty() && !type.isEmpty() && !deposit.isEmpty()) openAccount(id,type,deposit);
					else System.out.println("One of the inputs is missing");
					customerPage();
					break;
				case "2":
					System.out.println("CLOSE ACCOUNT");
					System.out.println("Account Number");
					String number = scanner.nextLine();
					if(!number.isEmpty()) closeAccount(number);
					else System.out.println("Invalid Input");
					customerPage();
					break;
				case "3":
					System.out.println("DEPOSIT MONEY");
					System.out.println("Account Number");
					number = scanner.nextLine();
					System.out.println("Deposit Amount");
					deposit = scanner.nextLine();
					if(!number.isEmpty() && !deposit.isEmpty()) deposit(number,deposit);
					else System.out.println("Invalid Input");
					customerPage();
					break;
				case "4":
					System.out.println( "WITHDRAW MONEY");
					System.out.println("Account Number");
					number = scanner.nextLine();
					System.out.println("Withdraw Amount");
					String withdraw = scanner.nextLine();
					if(!number.isEmpty() && !withdraw.isEmpty()) withdraw(number,withdraw);
					else System.out.println("Invalid Input");
					customerPage();
					break;
				case "5":
					System.out.println( "TRANSFER MONEY");
					System.out.println("Source Account Number");
					String source = scanner.nextLine();
					System.out.println("Destination Account Number");
					String destination = scanner.nextLine();
					System.out.println("Tranfer Amount");
					String amount = scanner.nextLine();
					if(!source.isEmpty() && !destination.isEmpty() && !amount.isEmpty()) transfer(source, destination, amount);
					else System.out.println("One of your inputs is empty");
					customerPage();
					break;
				case "6":
					System.out.println( "ACCOUNT SUMMARY FOR CUSTOMER ID: " + currentID );
					accountSummary(currentID);
					customerPage();
					break;
				case "7":
					welcomePage();
					break;
				default:
					customerPage();
					break;
			}
		}
	}
	private static void adminPage(){
		System.out.println("Administrator Page");
		System.out.println("1. Account Summary for a Customer\n" +
				"2. Report A :: Customer Information with Total Balance in Decreasing Order\n" +
				"3. Report B :: Find the Average Total Balance Between Age Groups\n" +
				"4. Back to welcome page");
		if(scanner.hasNextLine()){
			String input = scanner.nextLine();
			switch (input) {
				case "1":
					System.out.println("Please enter the customer ID");
					accountSummary(scanner.nextLine());
					adminPage();
					break;
				case "2":
					reportA();
					adminPage();
					break;
				case "3":
					System.out.println("Enter the age boundary.\nLower Bound Age");
					String lb = scanner.nextLine();
					System.out.println("Upper Bound Age");
					String ub = scanner.nextLine();
					if(!ub.isEmpty() && !lb.isEmpty()) reportB(lb,ub);
					else System.out.println("Invalid Input");
					adminPage();
					break;
				case "4":
					welcomePage();
					break;
			}
		}
	}

	private static void signupFunction(){
		System.out.println("This is the signup page. Please enter your name, gender, age, and PIN.\n" +
				"Name: ");
		String name = scanner.nextLine();
		System.out.println("Gender (in between F and M): ");
		String gender = scanner.nextLine();
		System.out.println("Age: ");
		String age = scanner.nextLine();
		System.out.println("PIN: ");
		String PIN = scanner.nextLine();
		if (!name.isEmpty() && !gender.isEmpty() && !age.isEmpty() && !PIN.isEmpty()) BankingSystem.newCustomer(name, gender.toUpperCase(), age, PIN);
		else {
			System.out.println("Invalid Input");
			welcomePage();
		}
	}

	private static void loginFunction(){
		System.out.println("This is the login page. Please enter your ID and PIN");
		System.out.println("Enter your ID");
		String ID = scanner.nextLine();
		System.out.println("Enter your PIN");
		String PIN = scanner.nextLine();
		if(ID.trim().equals("0") && PIN.trim().equals("0")){
			currentID = "0";
			adminPage();
		}
		else{
			boolean result = passwordCheck(ID, PIN);
			if(result){
				System.out.println(":: SUCCESS - Logged In Successfully");
				currentID = ID.toString();
				customerPage();
			}
			else System.out.println(":: ERROR - Validation Failed. Please try again");
		}

	}

	public static void newCustomer(String name, String gender, String age, String pin)
	{
		System.out.println("\n:: CREATE NEW CUSTOMER - RUNNING");
		try {
			con = DriverManager.getConnection(url, username, password);
			String queryNewCustomer = "SELECT ID FROM FINAL TABLE(INSERT INTO P1.CUSTOMER(NAME, GENDER, AGE, PIN) VALUES(?,?,?,?))";
			PreparedStatement pareparest = con.prepareStatement(queryNewCustomer);
			pareparest.setString(1, name);
			pareparest.setString(2, gender);
			pareparest.setInt(3, Integer.valueOf(age));
			pareparest.setInt(4, Integer.valueOf(pin));
			pareparest.executeQuery();
			rs = pareparest.getResultSet();
			if(rs.next()) {
				System.out.println(":: CREATE NEW CUSTOMER - SUCCESS");
			}
			pareparest.close();
			rs.close();
			con.close();
		} catch (SQLException e) {
			switch(e.getErrorCode()){
				case -545:
					System.out.println(":: ERROR - Invalid Input\n" +
							"Name (Letters Only)\n" +
							"Gender (F/M)\n" +
							"Age (>0)\n" +
							"PIN (>0)\n");
					welcomePage();
					break;
			}
		} catch (NumberFormatException e){
			System.out.println(":: FORMAT ERROR - " + e.getMessage() + ":: ERROR - Name can only be letters");
		}
	}

	public static boolean passwordCheck(String ID, String PIN)
	{
		try {
			Connection con = DriverManager.getConnection(url, username, password);
			Statement stmt = con.createStatement();
			String query = "SELECT PIN FROM P1.CUSTOMER WHERE ID = " + ID;
			rs = stmt.executeQuery(query);
			boolean empty = true;
			if (rs.next()) {
				int result = rs.getInt(1);
				empty = false;
				if(Integer.valueOf(PIN) == result) return true;
				else {
					System.out.println("UNMATCHED PIN");
					return false;
				}
			}
			if(empty) System.out.println(":: ERROR - No account is associated with: " + ID) ;
			rs.close();
			stmt.close();
			con.close();
		} catch (SQLException e) {
			System.out.println(":: ERROR");
			welcomePage();
		}
		catch (NumberFormatException e) {
			System.out.println(":: FORMAT ERROR -  " + e.getMessage() + " .Please try again.");
		}
		return false;
	}

	public static void openAccount(String id, String type, String amount) 
	{
		System.out.println("\n:: OPEN ACCOUNT - RUNNING");
		try {
			con = DriverManager.getConnection(url, username, password);
			String queryOpenAccount = "SELECT NUMBER FROM FINAL TABLE(INSERT INTO P1.ACCOUNT(ID, BALANCE, TYPE, STATUS) VALUES(?,?,?,?))";
			PreparedStatement pareparest = con.prepareStatement(queryOpenAccount);
			pareparest.setInt(1, Integer.valueOf(id));
			pareparest.setInt(2, Integer.valueOf(amount));
			pareparest.setString(3, type);
			pareparest.setString(4, "A");
			pareparest.executeQuery();
			rs = pareparest.getResultSet();
			if(rs.next()) {
				System.out.println(":: OPEN ACCOUNT - SUCCESS");
			}
			pareparest.close();
		} catch (SQLException e) {
			switch (e.getErrorCode()) {
				case -530:
					System.out.println(":: ERROR - ID: " + id + " does not existed in the customer table");
					break;
				case -545:
					System.out.println(":: ERROR - One of your inputs does not satisfy the constraints of the database.");
					break;

			}
		}
		catch (NumberFormatException e) {
			System.out.println(":: FORMAT ERROR - " + e.getMessage() + " .Please try again.");
		}
	}

	public static void closeAccount(String accNum) 
	{
		System.out.println("\n:: CLOSE ACCOUNT - RUNNING");
		if(isActive(accNum)){
			try {
				con = DriverManager.getConnection(url, username, password);
				String queryCloseAccount = "SELECT NUMBER FROM FINAL TABLE(UPDATE P1.ACCOUNT SET STATUS = 'I' WHERE NUMBER = ?)";
				PreparedStatement pareparest = con.prepareStatement(queryCloseAccount);
				pareparest.setInt(1, Integer.valueOf(accNum));
				rs = pareparest.executeQuery();
				while(rs.next()){
					int number = rs.getInt(1);
					if(number == Integer.valueOf(accNum)) System.out.println("\n:: CLOSE ACCOUNT - SUCCESS");

				}
				rs.close();
				pareparest.close();
				con.close();
			} catch (SQLException e) {
				System.out.println();

			} catch (NumberFormatException e){
				System.out.println(":: FORMAT ERROR - " + e.getMessage() + " .Please make sure ID and Deposit are numbers and enter C or S for account type.");
			}
		}

	}

	public static void deposit(String accNum, String amount) 
	{
		System.out.println("\n:: DEPOSIT - RUNNING");
		if(isActive(accNum)) {
			try {
				con = DriverManager.getConnection(url, username, password);
				String queryDeposit = "UPDATE P1.ACCOUNT SET BALANCE = BALANCE + ? WHERE NUMBER = ?";
				PreparedStatement pareparest = con.prepareStatement(queryDeposit);
				pareparest.setInt(1, Integer.valueOf(amount));
				pareparest.setInt(2, Integer.valueOf(accNum));
				pareparest.executeUpdate();
				pareparest.close();
				con.close();
				System.out.println(":: DEPOSIT - SUCCESS");
			} catch (SQLException e) {
				System.out.println();
				e.printStackTrace();
			}
		}

	}

	public static void withdraw(String accNum, String amount) 
	{
		System.out.println("\n:: WITHDRAW - RUNNING");
		if(isActive(accNum)) {
			try {
				con = DriverManager.getConnection(url, username, password);
				String queryDeposit = "UPDATE P1.ACCOUNT SET BALANCE = BALANCE - ? WHERE NUMBER = ?";
				PreparedStatement pareparest = con.prepareStatement(queryDeposit);
				pareparest.setInt(1, Integer.valueOf(amount));
				pareparest.setInt(2, Integer.valueOf(accNum));
				pareparest.executeUpdate();
				pareparest.close();
				con.close();
				System.out.println(":: WITHDRAW - SUCCESS");
			} catch (SQLException e) {
				System.out.println(":: WITHDRAW - ERROR. Please try again");
			} catch (NumberFormatException e){
				System.out.println(":: WITHDRAW - ERROR. Please make sure to enter NUMBERS for Account Number and Withdraw Amount");
			}
		}
	}

	public static void transfer(String srcAccNum, String destAccNum, String amount) 
	{
		System.out.println("\n:: TRANSFER - RUNNING");
		if(isActive(srcAccNum) && isActive(destAccNum)) {
			withdraw(srcAccNum, amount);
			deposit(destAccNum, amount);
			System.out.println(":: TRANSFER - SUCCESS");
		}
	}

	public static void accountSummary(String currentID)
	{
		StringBuilder sb=new StringBuilder();
		System.out.println("\n:: ACCOUNT SUMMARY - RUNNING");
		try {
			Connection con = DriverManager.getConnection(url, username, password);
			Statement stmt = con.createStatement();
			String query = "SELECT NUMBER, BALANCE FROM P1.ACCOUNT WHERE ID = " + currentID;
			ResultSet rs = stmt.executeQuery(query);
			sb.append(String.format(" %-10s","NUMBER"));
			sb.append(String.format(" %-10s\n","BALANCE"));
			sb.append(String.format(" %-10s","----------"));
			sb.append(String.format(" %-10s\n","----------"));
			boolean empty = true;
			while (rs.next()) {
				int number = rs.getInt(1);
				sb.append(String.format(" %10s",number));
				int balance = rs.getInt(2);
				sb.append(String.format(" %10s\n",balance));
				empty = false;
			}
			System.out.println(sb.toString());
			if(empty) System.out.println("No account is associated with this currentID: " + currentID);
			else System.out.println(":: ACCOUNT SUMMARY - SUCCESS");
			rs.close();
			stmt.close();
			con.close();
		} catch (SQLException e) {
			System.out.println(":: ACCOUNT SUMMARY - ERROR");
		}

	}

	public static void reportA() 
	{
		System.out.println("\n:: REPORT A - RUNNING");
		StringBuilder sb=new StringBuilder();
		try {
			Connection con = DriverManager.getConnection(url, username, password);
			Statement stmt = con.createStatement();
			String query = "SELECT B.ID, NAME, GENDER, AGE, PIN, TOTAL FROM P1.CUSTOMER C, P1.TOTAL_BALANCE B WHERE C.ID = B.ID ORDER BY TOTAL DESC";
			ResultSet rs = stmt.executeQuery(query);
			sb.append(String.format(" %-10s","ID"));
			sb.append(String.format(" %-10s","NAME"));
			sb.append(String.format(" %-10s","GENDER"));
			sb.append(String.format(" %-10s","AGE"));
			sb.append(String.format(" %-10s","PIN"));
			sb.append(String.format(" %-10s\n","TOTAL"));
			sb.append(String.format(" %-10s","----------"));
			sb.append(String.format(" %-10s","----------"));
			sb.append(String.format(" %-10s","----------"));
			sb.append(String.format(" %-10s","----------"));
			sb.append(String.format(" %-10s","----------"));
			sb.append(String.format(" %-10s\n","----------"));
			while (rs.next()) {
				int id = rs.getInt(1);
				sb.append(String.format(" %10s",id));
				String name = rs.getString(2);
				sb.append(String.format(" %10s",name));
				String gender = rs.getString(3);
				sb.append(String.format(" %10s",gender));
				int age = rs.getInt(4);
				sb.append(String.format(" %10s",age));
				int pin = rs.getInt(5);
				sb.append(String.format(" %10s",pin));
				int total = rs.getInt(6);
				sb.append(String.format(" %10s\n",total));
			}
			System.out.println(sb.toString());
			rs.close();
			stmt.close();
			con.close();
			System.out.println(":: REPORT A - SUCCESS");
		} catch (SQLException e) {
			System.out.println(":: REPORT A - ERROR READING THE DATABASE");
		}
	}

	public static void reportB(String min, String max) 
	{
		System.out.println("\n:: REPORT B - RUNNING");
		StringBuilder sb=new StringBuilder();
		try {
			Connection con = DriverManager.getConnection(url, username, password);
			Statement stmt = con.createStatement();
			String query = "SELECT AVG(TOTAL) AS AVERAGE FROM P1.TOTAL_BALANCE B, P1.CUSTOMER C WHERE C.ID = B.ID AND (C.AGE > " + min + " AND C.AGE < " + max + ") ";
			ResultSet rs = stmt.executeQuery(query);
			sb.append(String.format(" %-10s\n","AVERAGE"));
			sb.append(String.format(" %-10s\n","----------"));
			while (rs.next()) {
				int average = rs.getInt(1);
				sb.append(String.format(" %10s\n",average));
				System.out.println(":: REPORT B - SUCCESS");
			}
			System.out.println(sb.toString());
			rs.close();
			stmt.close();
			con.close();
		} catch (SQLException e) {
			System.out.println(":: REPORT B - ERROR");
			e.printStackTrace();
		} catch (NumberFormatException e) {
			System.out.println(":: FORMAT ERROR - " + e.getMessage() + " . Please make sure that ub and lb are NUMBERS");
		}
	}

	private static boolean isActive(String accNum) {
		try {
			con = DriverManager.getConnection(url, username, password);
			Statement stmt = con.createStatement();                                                
			String query = "SELECT STATUS FROM P1.ACCOUNT WHERE NUMBER = " + accNum;
			ResultSet rs = stmt.executeQuery(query);                                              
			boolean empty = true;
			while (rs.next()) {                                                                      
				String status = rs.getString(1);
				empty = false;
				if (status.equals("A")) return true;
				else {
					System.out.println(":: ERROR - This account " + accNum + " is currently inactive");
				}
			}
			if(empty){
				System.out.println(":: ERROR - This account " + accNum + " does not exist in our system");
				return false;
			}
			rs.close();                                                                            
			stmt.close();
		}catch (SQLException e) {
			System.out.println(":: DATABASE ERROR");
		}catch (NumberFormatException e) {
			System.out.println(":: FORMAT ERROR - " + e.getMessage() + " .Make sure account number is a NUMBER");
		}
		return false;
	}
}
